"""remove-entry-content-limit

Revision ID: 1c20682f0352
Revises: 9370a7a50804
Create Date: 2025-10-31 10:18:01.069811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c20682f0352'
down_revision: Union[str, Sequence[str], None] = '9370a7a50804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'content',
               existing_type=sa.String(length=10000),
               type_=sa.Text,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'content',
               existing_type=sa.Text,
               type_=sa.String(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###
