"""add progress column to entries table

Revision ID: 9370a7a50804
Revises: c9b35b64ffa4
Create Date: 2025-10-24 23:22:27.146212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9370a7a50804'
down_revision: Union[str, Sequence[str], None] = 'c9b35b64ffa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'progress')
    # ### end Alembic commands ###
